// One-off: for every concrete pack word, store its 25 nearest neighbours under the
// rank-averaged ensemble. Output is small and static; the game never needs vectors.
import { ranked, useModel } from "./neighbors";
import { PACK_WORDS } from "../../src/words/packs";
import { PACKS } from "../../src/game/config";
useModel("both");
const targets = [...new Set(Object.entries(PACK_WORDS).filter(([id]) => !PACKS[id]?.loose).flatMap(([, w]) => w))].sort();
const hubs: Record<string, string[]> = {};
for (const t of targets) hubs[t] = ranked(t).slice(0, 25).map((x) => x.w);
const src = "// Generated by proto/orbit/build-hubs.ts: each word's 25 nearest neighbours in meaning, nearest first\n// (rank-averaged across GloVe and a BGE embedding). Used by the Orbit game mode.\nexport const HUBS: Record<string, string[]> = " + JSON.stringify(hubs) + ";\n";
await Bun.write("src/words/hubs.ts", src);
console.log(`wrote ${targets.length} hubs, ${(src.length / 1024).toFixed(0)} KB`);
console.log("samples:", ["torch", "melon", "nurse", "piano", "storm", "otter"].map((t) => `${t}: ${hubs[t]?.slice(0, 6).join(" ")}`).join("\n         "));
