// One-off: the 25 nearest neighbours (rank-averaged ensemble) for EVERY answer word, so the
// Orbit board can draw relatedness between any two words on it. Separate from hubs.ts, which
// stays the curated target list.
import { ranked, useModel } from "./neighbors";
import { wordsForLength } from "../../src/words";
const ANSWERS = wordsForLength(5).answers;
useModel("both");
const out: Record<string, string[]> = {};
let n = 0;
for (const w of ANSWERS) {
  out[w] = ranked(w).slice(0, 25).map((x) => x.w);
  if (++n % 250 === 0) process.stdout.write(`${n}/${ANSWERS.length}\r`);
}
const src = "// Generated by proto/orbit/build-neighbors.ts: every answer's 25 nearest neighbours in meaning,\n// nearest first (rank-averaged across GloVe and a BGE embedding). Used to relate words on the Orbit board.\nexport const NEIGHBORS: Record<string, string[]> = " + JSON.stringify(out) + ";\n";
await Bun.write("src/words/neighbors.ts", src);
console.log(`\nwrote ${Object.keys(out).length} neighbour lists, ${(src.length / 1024).toFixed(0)} KB`);
